set_level:
  fields:
    level:
      required: true
      example: 70
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: box

trigger_event:
  fields:
    name:
      required: true
      example: "Fête FR"
      selector:
        text:

cancel_event:
  fields:
    name:
      required: true
      example: "Fête FR"
      selector:
        text:
